---
apiVersion: v1
kind: Pod
metadata:
  name: product
  labels:
    app: web
spec:
  containers:
    - name: product
      image:
      ports:
        - containerPort: 80
    - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5432
    - env:
        - name: POSTGRES_DB
          value: products_db
        - name: POSTGRES_USER
          value: dbuser
        - name: POSTGRES_PASSWORD
          value: password